// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.user;

import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserIdentityDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect UserIdentityDataOnDemand_Roo_Configurable {
    
    declare @type: UserIdentityDataOnDemand: @Configurable;
    
}
