// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.user;

import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserPassword;
import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserPasswordDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect UserPasswordDataOnDemand_Roo_DataOnDemand {
    
    declare @type: UserPasswordDataOnDemand: @Component;
    
    private Random UserPasswordDataOnDemand.rnd = new SecureRandom();
    
    private List<UserPassword> UserPasswordDataOnDemand.data;
    
    public UserPassword UserPasswordDataOnDemand.getNewTransientUserPassword(int index) {
        UserPassword obj = new UserPassword();
        setHash(obj, index);
        setSalt(obj, index);
        return obj;
    }
    
    public void UserPasswordDataOnDemand.setHash(UserPassword obj, int index) {
        String hash = "hash_" + index;
        obj.setHash(hash);
    }
    
    public void UserPasswordDataOnDemand.setSalt(UserPassword obj, int index) {
        String salt = "salt_" + index;
        obj.setSalt(salt);
    }
    
    public UserPassword UserPasswordDataOnDemand.getSpecificUserPassword(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        UserPassword obj = data.get(index);
        Long id = obj.getUserPasswordId();
        return UserPassword.findUserPassword(id);
    }
    
    public UserPassword UserPasswordDataOnDemand.getRandomUserPassword() {
        init();
        UserPassword obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getUserPasswordId();
        return UserPassword.findUserPassword(id);
    }
    
    public boolean UserPasswordDataOnDemand.modifyUserPassword(UserPassword obj) {
        return false;
    }
    
    public void UserPasswordDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = UserPassword.findUserPasswordEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'UserPassword' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<UserPassword>();
        for (int i = 0; i < 10; i++) {
            UserPassword obj = getNewTransientUserPassword(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
