// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.user;

import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserSession;
import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserSessionDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserSessionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserSessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserSessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserSessionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserSessionIntegrationTest: @Transactional;
    
    @Autowired
    private UserSessionDataOnDemand UserSessionIntegrationTest.dod;
    
    @Test
    public void UserSessionIntegrationTest.testCountUserSessions() {
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", dod.getRandomUserSession());
        long count = UserSession.countUserSessions();
        Assert.assertTrue("Counter for 'UserSession' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserSessionIntegrationTest.testFindUserSession() {
        UserSession obj = dod.getRandomUserSession();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", obj);
        Long id = obj.getUserSessionId();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to provide an identifier", id);
        obj = UserSession.findUserSession(id);
        Assert.assertNotNull("Find method for 'UserSession' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserSession' returned the incorrect identifier", id, obj.getUserSessionId());
    }
    
    @Test
    public void UserSessionIntegrationTest.testFindAllUserSessions() {
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", dod.getRandomUserSession());
        long count = UserSession.countUserSessions();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserSession', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserSession> result = UserSession.findAllUserSessions();
        Assert.assertNotNull("Find all method for 'UserSession' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserSession' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserSessionIntegrationTest.testFindUserSessionEntries() {
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", dod.getRandomUserSession());
        long count = UserSession.countUserSessions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserSession> result = UserSession.findUserSessionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserSession' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserSession' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserSessionIntegrationTest.testFlush() {
        UserSession obj = dod.getRandomUserSession();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", obj);
        Long id = obj.getUserSessionId();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to provide an identifier", id);
        obj = UserSession.findUserSession(id);
        Assert.assertNotNull("Find method for 'UserSession' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserSession(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserSession' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserSessionIntegrationTest.testMergeUpdate() {
        UserSession obj = dod.getRandomUserSession();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", obj);
        Long id = obj.getUserSessionId();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to provide an identifier", id);
        obj = UserSession.findUserSession(id);
        boolean modified =  dod.modifyUserSession(obj);
        Integer currentVersion = obj.getVersion();
        UserSession merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getUserSessionId(), id);
        Assert.assertTrue("Version for 'UserSession' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserSessionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", dod.getRandomUserSession());
        UserSession obj = dod.getNewTransientUserSession(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserSession' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserSession' identifier to be null", obj.getUserSessionId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserSession' identifier to no longer be null", obj.getUserSessionId());
    }
    
    @Test
    public void UserSessionIntegrationTest.testRemove() {
        UserSession obj = dod.getRandomUserSession();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to initialize correctly", obj);
        Long id = obj.getUserSessionId();
        Assert.assertNotNull("Data on demand for 'UserSession' failed to provide an identifier", id);
        obj = UserSession.findUserSession(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserSession' with identifier '" + id + "'", UserSession.findUserSession(id));
    }
    
}
