// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.user;

import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserPermission;
import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserPermissionDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.user.UserPermissionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect UserPermissionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserPermissionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserPermissionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: UserPermissionIntegrationTest: @Transactional;
    
    @Autowired
    private UserPermissionDataOnDemand UserPermissionIntegrationTest.dod;
    
    @Test
    public void UserPermissionIntegrationTest.testCountUserPermissions() {
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", dod.getRandomUserPermission());
        long count = UserPermission.countUserPermissions();
        Assert.assertTrue("Counter for 'UserPermission' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserPermissionIntegrationTest.testFindUserPermission() {
        UserPermission obj = dod.getRandomUserPermission();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", obj);
        Long id = obj.getUserPermissionId();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to provide an identifier", id);
        obj = UserPermission.findUserPermission(id);
        Assert.assertNotNull("Find method for 'UserPermission' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'UserPermission' returned the incorrect identifier", id, obj.getUserPermissionId());
    }
    
    @Test
    public void UserPermissionIntegrationTest.testFindAllUserPermissions() {
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", dod.getRandomUserPermission());
        long count = UserPermission.countUserPermissions();
        Assert.assertTrue("Too expensive to perform a find all test for 'UserPermission', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<UserPermission> result = UserPermission.findAllUserPermissions();
        Assert.assertNotNull("Find all method for 'UserPermission' illegally returned null", result);
        Assert.assertTrue("Find all method for 'UserPermission' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserPermissionIntegrationTest.testFindUserPermissionEntries() {
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", dod.getRandomUserPermission());
        long count = UserPermission.countUserPermissions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<UserPermission> result = UserPermission.findUserPermissionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'UserPermission' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'UserPermission' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserPermissionIntegrationTest.testFlush() {
        UserPermission obj = dod.getRandomUserPermission();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", obj);
        Long id = obj.getUserPermissionId();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to provide an identifier", id);
        obj = UserPermission.findUserPermission(id);
        Assert.assertNotNull("Find method for 'UserPermission' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserPermission(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'UserPermission' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserPermissionIntegrationTest.testMergeUpdate() {
        UserPermission obj = dod.getRandomUserPermission();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", obj);
        Long id = obj.getUserPermissionId();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to provide an identifier", id);
        obj = UserPermission.findUserPermission(id);
        boolean modified =  dod.modifyUserPermission(obj);
        Integer currentVersion = obj.getVersion();
        UserPermission merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getUserPermissionId(), id);
        Assert.assertTrue("Version for 'UserPermission' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserPermissionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", dod.getRandomUserPermission());
        UserPermission obj = dod.getNewTransientUserPermission(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'UserPermission' identifier to be null", obj.getUserPermissionId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'UserPermission' identifier to no longer be null", obj.getUserPermissionId());
    }
    
    @Test
    public void UserPermissionIntegrationTest.testRemove() {
        UserPermission obj = dod.getRandomUserPermission();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to initialize correctly", obj);
        Long id = obj.getUserPermissionId();
        Assert.assertNotNull("Data on demand for 'UserPermission' failed to provide an identifier", id);
        obj = UserPermission.findUserPermission(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'UserPermission' with identifier '" + id + "'", UserPermission.findUserPermission(id));
    }
    
}
