// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.study;

import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Language;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.LanguageDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.LanguageIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LanguageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LanguageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LanguageIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: LanguageIntegrationTest: @Transactional;
    
    @Autowired
    private LanguageDataOnDemand LanguageIntegrationTest.dod;
    
    @Test
    public void LanguageIntegrationTest.testCountLanguages() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = Language.countLanguages();
        Assert.assertTrue("Counter for 'Language' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LanguageIntegrationTest.testFindLanguage() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Long id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = Language.findLanguage(id);
        Assert.assertNotNull("Find method for 'Language' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Language' returned the incorrect identifier", id, obj.getLanguageId());
    }
    
    @Test
    public void LanguageIntegrationTest.testFindAllLanguages() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = Language.countLanguages();
        Assert.assertTrue("Too expensive to perform a find all test for 'Language', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Language> result = Language.findAllLanguages();
        Assert.assertNotNull("Find all method for 'Language' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Language' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LanguageIntegrationTest.testFindLanguageEntries() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        long count = Language.countLanguages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Language> result = Language.findLanguageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Language' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Language' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LanguageIntegrationTest.testFlush() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Long id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = Language.findLanguage(id);
        Assert.assertNotNull("Find method for 'Language' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLanguage(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Language' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LanguageIntegrationTest.testMergeUpdate() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Long id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = Language.findLanguage(id);
        boolean modified =  dod.modifyLanguage(obj);
        Integer currentVersion = obj.getVersion();
        Language merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getLanguageId(), id);
        Assert.assertTrue("Version for 'Language' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LanguageIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", dod.getRandomLanguage());
        Language obj = dod.getNewTransientLanguage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Language' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Language' identifier to be null", obj.getLanguageId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Language' identifier to no longer be null", obj.getLanguageId());
    }
    
    @Test
    public void LanguageIntegrationTest.testRemove() {
        Language obj = dod.getRandomLanguage();
        Assert.assertNotNull("Data on demand for 'Language' failed to initialize correctly", obj);
        Long id = obj.getLanguageId();
        Assert.assertNotNull("Data on demand for 'Language' failed to provide an identifier", id);
        obj = Language.findLanguage(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Language' with identifier '" + id + "'", Language.findLanguage(id));
    }
    
}
