// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.study;

import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Degree;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.DegreeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Language;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Programme;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.ProgrammeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.StudyMode;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.StudyModeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProgrammeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProgrammeDataOnDemand: @Component;
    
    private Random ProgrammeDataOnDemand.rnd = new SecureRandom();
    
    private List<Programme> ProgrammeDataOnDemand.data;
    
    @Autowired
    private DegreeDataOnDemand ProgrammeDataOnDemand.degreeDataOnDemand;
    
    @Autowired
    private StudyModeDataOnDemand ProgrammeDataOnDemand.studyModeDataOnDemand;
    
    public Programme ProgrammeDataOnDemand.getNewTransientProgramme(int index) {
        Programme obj = new Programme();
        setDegree(obj, index);
        setLanguage(obj, index);
        setName(obj, index);
        setStudyMode(obj, index);
        return obj;
    }
    
    public void ProgrammeDataOnDemand.setDegree(Programme obj, int index) {
        Degree degree = degreeDataOnDemand.getRandomDegree();
        obj.setDegree(degree);
    }
    
    public void ProgrammeDataOnDemand.setLanguage(Programme obj, int index) {
        Language language = null;
        obj.setLanguage(language);
    }
    
    public void ProgrammeDataOnDemand.setName(Programme obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void ProgrammeDataOnDemand.setStudyMode(Programme obj, int index) {
        StudyMode studyMode = studyModeDataOnDemand.getRandomStudyMode();
        obj.setStudyMode(studyMode);
    }
    
    public Programme ProgrammeDataOnDemand.getSpecificProgramme(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Programme obj = data.get(index);
        Long id = obj.getProgrammeId();
        return Programme.findProgramme(id);
    }
    
    public Programme ProgrammeDataOnDemand.getRandomProgramme() {
        init();
        Programme obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getProgrammeId();
        return Programme.findProgramme(id);
    }
    
    public boolean ProgrammeDataOnDemand.modifyProgramme(Programme obj) {
        return false;
    }
    
    public void ProgrammeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Programme.findProgrammeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Programme' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Programme>();
        for (int i = 0; i < 10; i++) {
            Programme obj = getNewTransientProgramme(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
