// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.address;

import cz.cvut.fit.mi_mpr_dip.admission.domain.address.City;
import javax.persistence.Entity;

privileged aspect City_Roo_Jpa_Entity {
    
    declare @type: City: @Entity;
    
}
