// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.study;

import javax.persistence.Entity;

privileged aspect Language_Roo_Jpa_Entity {
    
    declare @type: Language: @Entity;
    
}
