// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.Admission;
import cz.cvut.fit.mi_mpr_dip.admission.domain.AdmissionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AdmissionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdmissionDataOnDemand: @Component;
    
    private Random AdmissionDataOnDemand.rnd = new SecureRandom();
    
    private List<Admission> AdmissionDataOnDemand.data;
    
    public Admission AdmissionDataOnDemand.getNewTransientAdmission(int index) {
        Admission obj = new Admission();
        return obj;
    }
    
    public Admission AdmissionDataOnDemand.getSpecificAdmission(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Admission obj = data.get(index);
        Long id = obj.getId();
        return Admission.findAdmission(id);
    }
    
    public Admission AdmissionDataOnDemand.getRandomAdmission() {
        init();
        Admission obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Admission.findAdmission(id);
    }
    
    public boolean AdmissionDataOnDemand.modifyAdmission(Admission obj) {
        return false;
    }
    
    public void AdmissionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Admission.findAdmissionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Admission' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Admission>();
        for (int i = 0; i < 10; i++) {
            Admission obj = getNewTransientAdmission(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
