// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.AdmissionState;
import cz.cvut.fit.mi_mpr_dip.admission.domain.AdmissionStateDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AdmissionStateDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AdmissionStateDataOnDemand: @Component;
    
    private Random AdmissionStateDataOnDemand.rnd = new SecureRandom();
    
    private List<AdmissionState> AdmissionStateDataOnDemand.data;
    
    public AdmissionState AdmissionStateDataOnDemand.getNewTransientAdmissionState(int index) {
        AdmissionState obj = new AdmissionState();
        setCode(obj, index);
        setDesciption(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void AdmissionStateDataOnDemand.setCode(AdmissionState obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void AdmissionStateDataOnDemand.setDesciption(AdmissionState obj, int index) {
        String desciption = "desciption_" + index;
        obj.setDesciption(desciption);
    }
    
    public void AdmissionStateDataOnDemand.setName(AdmissionState obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public AdmissionState AdmissionStateDataOnDemand.getSpecificAdmissionState(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AdmissionState obj = data.get(index);
        Long id = obj.getAdmissionStateId();
        return AdmissionState.findAdmissionState(id);
    }
    
    public AdmissionState AdmissionStateDataOnDemand.getRandomAdmissionState() {
        init();
        AdmissionState obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getAdmissionStateId();
        return AdmissionState.findAdmissionState(id);
    }
    
    public boolean AdmissionStateDataOnDemand.modifyAdmissionState(AdmissionState obj) {
        return false;
    }
    
    public void AdmissionStateDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AdmissionState.findAdmissionStateEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AdmissionState' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AdmissionState>();
        for (int i = 0; i < 10; i++) {
            AdmissionState obj = getNewTransientAdmissionState(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
