// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.Appeal;
import cz.cvut.fit.mi_mpr_dip.admission.domain.AppealDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.AppealTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect AppealDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppealDataOnDemand: @Component;
    
    private Random AppealDataOnDemand.rnd = new SecureRandom();
    
    private List<Appeal> AppealDataOnDemand.data;
    
    @Autowired
    private AppealTypeDataOnDemand AppealDataOnDemand.appealTypeDataOnDemand;
    
    public Appeal AppealDataOnDemand.getNewTransientAppeal(int index) {
        Appeal obj = new Appeal();
        setAccepted(obj, index);
        return obj;
    }
    
    public void AppealDataOnDemand.setAccepted(Appeal obj, int index) {
        Boolean accepted = Boolean.TRUE;
        obj.setAccepted(accepted);
    }
    
    public Appeal AppealDataOnDemand.getSpecificAppeal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Appeal obj = data.get(index);
        Long id = obj.getAppealId();
        return Appeal.findAppeal(id);
    }
    
    public Appeal AppealDataOnDemand.getRandomAppeal() {
        init();
        Appeal obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getAppealId();
        return Appeal.findAppeal(id);
    }
    
    public boolean AppealDataOnDemand.modifyAppeal(Appeal obj) {
        return false;
    }
    
    public void AppealDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Appeal.findAppealEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Appeal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Appeal>();
        for (int i = 0; i < 10; i++) {
            Appeal obj = getNewTransientAppeal(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
