// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.Evaluation;
import cz.cvut.fit.mi_mpr_dip.admission.domain.EvaluationDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.EvaluationTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect EvaluationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EvaluationDataOnDemand: @Component;
    
    private Random EvaluationDataOnDemand.rnd = new SecureRandom();
    
    private List<Evaluation> EvaluationDataOnDemand.data;
    
    @Autowired
    private EvaluationTypeDataOnDemand EvaluationDataOnDemand.evaluationTypeDataOnDemand;
    
    public Evaluation EvaluationDataOnDemand.getNewTransientEvaluation(int index) {
        Evaluation obj = new Evaluation();
        setValue(obj, index);
        return obj;
    }
    
    public void EvaluationDataOnDemand.setValue(Evaluation obj, int index) {
        String value = "value_" + index;
        obj.setValue(value);
    }
    
    public Evaluation EvaluationDataOnDemand.getSpecificEvaluation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Evaluation obj = data.get(index);
        Long id = obj.getEvaluationId();
        return Evaluation.findEvaluation(id);
    }
    
    public Evaluation EvaluationDataOnDemand.getRandomEvaluation() {
        init();
        Evaluation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getEvaluationId();
        return Evaluation.findEvaluation(id);
    }
    
    public boolean EvaluationDataOnDemand.modifyEvaluation(Evaluation obj) {
        return false;
    }
    
    public void EvaluationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Evaluation.findEvaluationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Evaluation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Evaluation>();
        for (int i = 0; i < 10; i++) {
            Evaluation obj = getNewTransientEvaluation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
