// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.Photo;
import cz.cvut.fit.mi_mpr_dip.admission.domain.PhotoDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PhotoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PhotoDataOnDemand: @Component;
    
    private Random PhotoDataOnDemand.rnd = new SecureRandom();
    
    private List<Photo> PhotoDataOnDemand.data;
    
    public Photo PhotoDataOnDemand.getNewTransientPhoto(int index) {
        Photo obj = new Photo();
        setContent(obj, index);
        setFilename(obj, index);
        setMimeType(obj, index);
        return obj;
    }
    
    public void PhotoDataOnDemand.setContent(Photo obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public void PhotoDataOnDemand.setFilename(Photo obj, int index) {
        String filename = "filename_" + index;
        obj.setFilename(filename);
    }
    
    public void PhotoDataOnDemand.setMimeType(Photo obj, int index) {
        String mimeType = "mimeType_" + index;
        obj.setMimeType(mimeType);
    }
    
    public Photo PhotoDataOnDemand.getSpecificPhoto(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Photo obj = data.get(index);
        Long id = obj.getPhotoId();
        return Photo.findPhoto(id);
    }
    
    public Photo PhotoDataOnDemand.getRandomPhoto() {
        init();
        Photo obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getPhotoId();
        return Photo.findPhoto(id);
    }
    
    public boolean PhotoDataOnDemand.modifyPhoto(Photo obj) {
        return false;
    }
    
    public void PhotoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Photo.findPhotoEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Photo' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Photo>();
        for (int i = 0; i < 10; i++) {
            Photo obj = getNewTransientPhoto(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
