// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.Photo;
import cz.cvut.fit.mi_mpr_dip.admission.domain.PhotoDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.PhotoIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhotoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhotoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhotoIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhotoIntegrationTest: @Transactional;
    
    @Autowired
    private PhotoDataOnDemand PhotoIntegrationTest.dod;
    
    @Test
    public void PhotoIntegrationTest.testCountPhotos() {
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", dod.getRandomPhoto());
        long count = Photo.countPhotos();
        Assert.assertTrue("Counter for 'Photo' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhotoIntegrationTest.testFindPhoto() {
        Photo obj = dod.getRandomPhoto();
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", obj);
        Long id = obj.getPhotoId();
        Assert.assertNotNull("Data on demand for 'Photo' failed to provide an identifier", id);
        obj = Photo.findPhoto(id);
        Assert.assertNotNull("Find method for 'Photo' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Photo' returned the incorrect identifier", id, obj.getPhotoId());
    }
    
    @Test
    public void PhotoIntegrationTest.testFindAllPhotos() {
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", dod.getRandomPhoto());
        long count = Photo.countPhotos();
        Assert.assertTrue("Too expensive to perform a find all test for 'Photo', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Photo> result = Photo.findAllPhotos();
        Assert.assertNotNull("Find all method for 'Photo' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Photo' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhotoIntegrationTest.testFindPhotoEntries() {
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", dod.getRandomPhoto());
        long count = Photo.countPhotos();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Photo> result = Photo.findPhotoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Photo' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Photo' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhotoIntegrationTest.testFlush() {
        Photo obj = dod.getRandomPhoto();
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", obj);
        Long id = obj.getPhotoId();
        Assert.assertNotNull("Data on demand for 'Photo' failed to provide an identifier", id);
        obj = Photo.findPhoto(id);
        Assert.assertNotNull("Find method for 'Photo' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhoto(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Photo' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhotoIntegrationTest.testMergeUpdate() {
        Photo obj = dod.getRandomPhoto();
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", obj);
        Long id = obj.getPhotoId();
        Assert.assertNotNull("Data on demand for 'Photo' failed to provide an identifier", id);
        obj = Photo.findPhoto(id);
        boolean modified =  dod.modifyPhoto(obj);
        Integer currentVersion = obj.getVersion();
        Photo merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getPhotoId(), id);
        Assert.assertTrue("Version for 'Photo' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhotoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", dod.getRandomPhoto());
        Photo obj = dod.getNewTransientPhoto(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Photo' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Photo' identifier to be null", obj.getPhotoId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Photo' identifier to no longer be null", obj.getPhotoId());
    }
    
    @Test
    public void PhotoIntegrationTest.testRemove() {
        Photo obj = dod.getRandomPhoto();
        Assert.assertNotNull("Data on demand for 'Photo' failed to initialize correctly", obj);
        Long id = obj.getPhotoId();
        Assert.assertNotNull("Data on demand for 'Photo' failed to provide an identifier", id);
        obj = Photo.findPhoto(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Photo' with identifier '" + id + "'", Photo.findPhoto(id));
    }
    
}
