// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.ProgrammeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.ProgrammeIntegrationTest;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Programme;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ProgrammeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProgrammeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProgrammeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProgrammeIntegrationTest: @Transactional;
    
    @Autowired
    private ProgrammeDataOnDemand ProgrammeIntegrationTest.dod;
    
    @Test
    public void ProgrammeIntegrationTest.testCountProgrammes() {
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", dod.getRandomProgramme());
        long count = Programme.countProgrammes();
        Assert.assertTrue("Counter for 'Programme' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProgrammeIntegrationTest.testFindProgramme() {
        Programme obj = dod.getRandomProgramme();
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Programme' failed to provide an identifier", id);
        obj = Programme.findProgramme(id);
        Assert.assertNotNull("Find method for 'Programme' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Programme' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProgrammeIntegrationTest.testFindAllProgrammes() {
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", dod.getRandomProgramme());
        long count = Programme.countProgrammes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Programme', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Programme> result = Programme.findAllProgrammes();
        Assert.assertNotNull("Find all method for 'Programme' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Programme' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProgrammeIntegrationTest.testFindProgrammeEntries() {
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", dod.getRandomProgramme());
        long count = Programme.countProgrammes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Programme> result = Programme.findProgrammeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Programme' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Programme' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProgrammeIntegrationTest.testFlush() {
        Programme obj = dod.getRandomProgramme();
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Programme' failed to provide an identifier", id);
        obj = Programme.findProgramme(id);
        Assert.assertNotNull("Find method for 'Programme' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProgramme(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Programme' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProgrammeIntegrationTest.testMergeUpdate() {
        Programme obj = dod.getRandomProgramme();
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Programme' failed to provide an identifier", id);
        obj = Programme.findProgramme(id);
        boolean modified =  dod.modifyProgramme(obj);
        Integer currentVersion = obj.getVersion();
        Programme merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Programme' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProgrammeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", dod.getRandomProgramme());
        Programme obj = dod.getNewTransientProgramme(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Programme' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Programme' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Programme' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProgrammeIntegrationTest.testRemove() {
        Programme obj = dod.getRandomProgramme();
        Assert.assertNotNull("Data on demand for 'Programme' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Programme' failed to provide an identifier", id);
        obj = Programme.findProgramme(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Programme' with identifier '" + id + "'", Programme.findProgramme(id));
    }
    
}
