// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.ProgrammeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.Programme;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect ProgrammeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProgrammeDataOnDemand: @Component;
    
    private Random ProgrammeDataOnDemand.rnd = new SecureRandom();
    
    private List<Programme> ProgrammeDataOnDemand.data;
    
    public Programme ProgrammeDataOnDemand.getNewTransientProgramme(int index) {
        Programme obj = new Programme();
        return obj;
    }
    
    public Programme ProgrammeDataOnDemand.getSpecificProgramme(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Programme obj = data.get(index);
        Long id = obj.getId();
        return Programme.findProgramme(id);
    }
    
    public Programme ProgrammeDataOnDemand.getRandomProgramme() {
        init();
        Programme obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Programme.findProgramme(id);
    }
    
    public boolean ProgrammeDataOnDemand.modifyProgramme(Programme obj) {
        return false;
    }
    
    public void ProgrammeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Programme.findProgrammeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Programme' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Programme>();
        for (int i = 0; i < 10; i++) {
            Programme obj = getNewTransientProgramme(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
