// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumber;
import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumberDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumberIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReferenceNumberIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReferenceNumberIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReferenceNumberIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReferenceNumberIntegrationTest: @Transactional;
    
    @Autowired
    private ReferenceNumberDataOnDemand ReferenceNumberIntegrationTest.dod;
    
    @Test
    public void ReferenceNumberIntegrationTest.testCountReferenceNumbers() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", dod.getRandomReferenceNumber());
        long count = ReferenceNumber.countReferenceNumbers();
        Assert.assertTrue("Counter for 'ReferenceNumber' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testFindReferenceNumber() {
        ReferenceNumber obj = dod.getRandomReferenceNumber();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to provide an identifier", id);
        obj = ReferenceNumber.findReferenceNumber(id);
        Assert.assertNotNull("Find method for 'ReferenceNumber' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReferenceNumber' returned the incorrect identifier", id, obj.getReferenceNumberId());
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testFindAllReferenceNumbers() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", dod.getRandomReferenceNumber());
        long count = ReferenceNumber.countReferenceNumbers();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReferenceNumber', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReferenceNumber> result = ReferenceNumber.findAllReferenceNumbers();
        Assert.assertNotNull("Find all method for 'ReferenceNumber' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReferenceNumber' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testFindReferenceNumberEntries() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", dod.getRandomReferenceNumber());
        long count = ReferenceNumber.countReferenceNumbers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReferenceNumber> result = ReferenceNumber.findReferenceNumberEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReferenceNumber' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReferenceNumber' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testFlush() {
        ReferenceNumber obj = dod.getRandomReferenceNumber();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to provide an identifier", id);
        obj = ReferenceNumber.findReferenceNumber(id);
        Assert.assertNotNull("Find method for 'ReferenceNumber' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReferenceNumber(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ReferenceNumber' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testMergeUpdate() {
        ReferenceNumber obj = dod.getRandomReferenceNumber();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to provide an identifier", id);
        obj = ReferenceNumber.findReferenceNumber(id);
        boolean modified =  dod.modifyReferenceNumber(obj);
        Integer currentVersion = obj.getVersion();
        ReferenceNumber merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getReferenceNumberId(), id);
        Assert.assertTrue("Version for 'ReferenceNumber' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", dod.getRandomReferenceNumber());
        ReferenceNumber obj = dod.getNewTransientReferenceNumber(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReferenceNumber' identifier to be null", obj.getReferenceNumberId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ReferenceNumber' identifier to no longer be null", obj.getReferenceNumberId());
    }
    
    @Test
    public void ReferenceNumberIntegrationTest.testRemove() {
        ReferenceNumber obj = dod.getRandomReferenceNumber();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumber' failed to provide an identifier", id);
        obj = ReferenceNumber.findReferenceNumber(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ReferenceNumber' with identifier '" + id + "'", ReferenceNumber.findReferenceNumber(id));
    }
    
}
