// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumberType;
import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumberTypeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.ReferenceNumberTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReferenceNumberTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReferenceNumberTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReferenceNumberTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReferenceNumberTypeIntegrationTest: @Transactional;
    
    @Autowired
    private ReferenceNumberTypeDataOnDemand ReferenceNumberTypeIntegrationTest.dod;
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testCountReferenceNumberTypes() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", dod.getRandomReferenceNumberType());
        long count = ReferenceNumberType.countReferenceNumberTypes();
        Assert.assertTrue("Counter for 'ReferenceNumberType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testFindReferenceNumberType() {
        ReferenceNumberType obj = dod.getRandomReferenceNumberType();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberTypeId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to provide an identifier", id);
        obj = ReferenceNumberType.findReferenceNumberType(id);
        Assert.assertNotNull("Find method for 'ReferenceNumberType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ReferenceNumberType' returned the incorrect identifier", id, obj.getReferenceNumberTypeId());
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testFindAllReferenceNumberTypes() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", dod.getRandomReferenceNumberType());
        long count = ReferenceNumberType.countReferenceNumberTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'ReferenceNumberType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ReferenceNumberType> result = ReferenceNumberType.findAllReferenceNumberTypes();
        Assert.assertNotNull("Find all method for 'ReferenceNumberType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ReferenceNumberType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testFindReferenceNumberTypeEntries() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", dod.getRandomReferenceNumberType());
        long count = ReferenceNumberType.countReferenceNumberTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ReferenceNumberType> result = ReferenceNumberType.findReferenceNumberTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ReferenceNumberType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ReferenceNumberType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testFlush() {
        ReferenceNumberType obj = dod.getRandomReferenceNumberType();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberTypeId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to provide an identifier", id);
        obj = ReferenceNumberType.findReferenceNumberType(id);
        Assert.assertNotNull("Find method for 'ReferenceNumberType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReferenceNumberType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ReferenceNumberType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testMergeUpdate() {
        ReferenceNumberType obj = dod.getRandomReferenceNumberType();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberTypeId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to provide an identifier", id);
        obj = ReferenceNumberType.findReferenceNumberType(id);
        boolean modified =  dod.modifyReferenceNumberType(obj);
        Integer currentVersion = obj.getVersion();
        ReferenceNumberType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getReferenceNumberTypeId(), id);
        Assert.assertTrue("Version for 'ReferenceNumberType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", dod.getRandomReferenceNumberType());
        ReferenceNumberType obj = dod.getNewTransientReferenceNumberType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ReferenceNumberType' identifier to be null", obj.getReferenceNumberTypeId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ReferenceNumberType' identifier to no longer be null", obj.getReferenceNumberTypeId());
    }
    
    @Test
    public void ReferenceNumberTypeIntegrationTest.testRemove() {
        ReferenceNumberType obj = dod.getRandomReferenceNumberType();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to initialize correctly", obj);
        Long id = obj.getReferenceNumberTypeId();
        Assert.assertNotNull("Data on demand for 'ReferenceNumberType' failed to provide an identifier", id);
        obj = ReferenceNumberType.findReferenceNumberType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ReferenceNumberType' with identifier '" + id + "'", ReferenceNumberType.findReferenceNumberType(id));
    }
    
}
