// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.StudyModeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.StudyModeIntegrationTest;
import cz.cvut.fit.mi_mpr_dip.admission.domain.study.StudyMode;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudyModeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudyModeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudyModeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudyModeIntegrationTest: @Transactional;
    
    @Autowired
    private StudyModeDataOnDemand StudyModeIntegrationTest.dod;
    
    @Test
    public void StudyModeIntegrationTest.testCountStudyModes() {
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", dod.getRandomStudyMode());
        long count = StudyMode.countStudyModes();
        Assert.assertTrue("Counter for 'StudyMode' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudyModeIntegrationTest.testFindStudyMode() {
        StudyMode obj = dod.getRandomStudyMode();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to provide an identifier", id);
        obj = StudyMode.findStudyMode(id);
        Assert.assertNotNull("Find method for 'StudyMode' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudyMode' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudyModeIntegrationTest.testFindAllStudyModes() {
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", dod.getRandomStudyMode());
        long count = StudyMode.countStudyModes();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudyMode', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudyMode> result = StudyMode.findAllStudyModes();
        Assert.assertNotNull("Find all method for 'StudyMode' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudyMode' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudyModeIntegrationTest.testFindStudyModeEntries() {
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", dod.getRandomStudyMode());
        long count = StudyMode.countStudyModes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudyMode> result = StudyMode.findStudyModeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudyMode' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudyMode' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudyModeIntegrationTest.testFlush() {
        StudyMode obj = dod.getRandomStudyMode();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to provide an identifier", id);
        obj = StudyMode.findStudyMode(id);
        Assert.assertNotNull("Find method for 'StudyMode' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStudyMode(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StudyMode' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudyModeIntegrationTest.testMergeUpdate() {
        StudyMode obj = dod.getRandomStudyMode();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to provide an identifier", id);
        obj = StudyMode.findStudyMode(id);
        boolean modified =  dod.modifyStudyMode(obj);
        Integer currentVersion = obj.getVersion();
        StudyMode merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StudyMode' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudyModeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", dod.getRandomStudyMode());
        StudyMode obj = dod.getNewTransientStudyMode(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudyMode' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StudyMode' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudyModeIntegrationTest.testRemove() {
        StudyMode obj = dod.getRandomStudyMode();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyMode' failed to provide an identifier", id);
        obj = StudyMode.findStudyMode(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudyMode' with identifier '" + id + "'", StudyMode.findStudyMode(id));
    }
    
}
