// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.TermRegistration;
import cz.cvut.fit.mi_mpr_dip.admission.domain.TermRegistrationDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.TermRegistrationIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TermRegistrationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TermRegistrationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TermRegistrationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TermRegistrationIntegrationTest: @Transactional;
    
    @Autowired
    private TermRegistrationDataOnDemand TermRegistrationIntegrationTest.dod;
    
    @Test
    public void TermRegistrationIntegrationTest.testCountTermRegistrations() {
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", dod.getRandomTermRegistration());
        long count = TermRegistration.countTermRegistrations();
        Assert.assertTrue("Counter for 'TermRegistration' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testFindTermRegistration() {
        TermRegistration obj = dod.getRandomTermRegistration();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", obj);
        Long id = obj.getTermRegistrationId();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to provide an identifier", id);
        obj = TermRegistration.findTermRegistration(id);
        Assert.assertNotNull("Find method for 'TermRegistration' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TermRegistration' returned the incorrect identifier", id, obj.getTermRegistrationId());
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testFindAllTermRegistrations() {
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", dod.getRandomTermRegistration());
        long count = TermRegistration.countTermRegistrations();
        Assert.assertTrue("Too expensive to perform a find all test for 'TermRegistration', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TermRegistration> result = TermRegistration.findAllTermRegistrations();
        Assert.assertNotNull("Find all method for 'TermRegistration' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TermRegistration' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testFindTermRegistrationEntries() {
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", dod.getRandomTermRegistration());
        long count = TermRegistration.countTermRegistrations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TermRegistration> result = TermRegistration.findTermRegistrationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TermRegistration' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TermRegistration' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testFlush() {
        TermRegistration obj = dod.getRandomTermRegistration();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", obj);
        Long id = obj.getTermRegistrationId();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to provide an identifier", id);
        obj = TermRegistration.findTermRegistration(id);
        Assert.assertNotNull("Find method for 'TermRegistration' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTermRegistration(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TermRegistration' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testMergeUpdate() {
        TermRegistration obj = dod.getRandomTermRegistration();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", obj);
        Long id = obj.getTermRegistrationId();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to provide an identifier", id);
        obj = TermRegistration.findTermRegistration(id);
        boolean modified =  dod.modifyTermRegistration(obj);
        Integer currentVersion = obj.getVersion();
        TermRegistration merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getTermRegistrationId(), id);
        Assert.assertTrue("Version for 'TermRegistration' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", dod.getRandomTermRegistration());
        TermRegistration obj = dod.getNewTransientTermRegistration(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TermRegistration' identifier to be null", obj.getTermRegistrationId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TermRegistration' identifier to no longer be null", obj.getTermRegistrationId());
    }
    
    @Test
    public void TermRegistrationIntegrationTest.testRemove() {
        TermRegistration obj = dod.getRandomTermRegistration();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to initialize correctly", obj);
        Long id = obj.getTermRegistrationId();
        Assert.assertNotNull("Data on demand for 'TermRegistration' failed to provide an identifier", id);
        obj = TermRegistration.findTermRegistration(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TermRegistration' with identifier '" + id + "'", TermRegistration.findTermRegistration(id));
    }
    
}
