// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain;

import cz.cvut.fit.mi_mpr_dip.admission.domain.TermType;
import cz.cvut.fit.mi_mpr_dip.admission.domain.TermTypeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.TermTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TermTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TermTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TermTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TermTypeIntegrationTest: @Transactional;
    
    @Autowired
    private TermTypeDataOnDemand TermTypeIntegrationTest.dod;
    
    @Test
    public void TermTypeIntegrationTest.testCountTermTypes() {
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", dod.getRandomTermType());
        long count = TermType.countTermTypes();
        Assert.assertTrue("Counter for 'TermType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TermTypeIntegrationTest.testFindTermType() {
        TermType obj = dod.getRandomTermType();
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", obj);
        Long id = obj.getTermTypeId();
        Assert.assertNotNull("Data on demand for 'TermType' failed to provide an identifier", id);
        obj = TermType.findTermType(id);
        Assert.assertNotNull("Find method for 'TermType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'TermType' returned the incorrect identifier", id, obj.getTermTypeId());
    }
    
    @Test
    public void TermTypeIntegrationTest.testFindAllTermTypes() {
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", dod.getRandomTermType());
        long count = TermType.countTermTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'TermType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<TermType> result = TermType.findAllTermTypes();
        Assert.assertNotNull("Find all method for 'TermType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'TermType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TermTypeIntegrationTest.testFindTermTypeEntries() {
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", dod.getRandomTermType());
        long count = TermType.countTermTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<TermType> result = TermType.findTermTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'TermType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'TermType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TermTypeIntegrationTest.testFlush() {
        TermType obj = dod.getRandomTermType();
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", obj);
        Long id = obj.getTermTypeId();
        Assert.assertNotNull("Data on demand for 'TermType' failed to provide an identifier", id);
        obj = TermType.findTermType(id);
        Assert.assertNotNull("Find method for 'TermType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTermType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'TermType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermTypeIntegrationTest.testMergeUpdate() {
        TermType obj = dod.getRandomTermType();
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", obj);
        Long id = obj.getTermTypeId();
        Assert.assertNotNull("Data on demand for 'TermType' failed to provide an identifier", id);
        obj = TermType.findTermType(id);
        boolean modified =  dod.modifyTermType(obj);
        Integer currentVersion = obj.getVersion();
        TermType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getTermTypeId(), id);
        Assert.assertTrue("Version for 'TermType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TermTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", dod.getRandomTermType());
        TermType obj = dod.getNewTransientTermType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'TermType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'TermType' identifier to be null", obj.getTermTypeId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'TermType' identifier to no longer be null", obj.getTermTypeId());
    }
    
    @Test
    public void TermTypeIntegrationTest.testRemove() {
        TermType obj = dod.getRandomTermType();
        Assert.assertNotNull("Data on demand for 'TermType' failed to initialize correctly", obj);
        Long id = obj.getTermTypeId();
        Assert.assertNotNull("Data on demand for 'TermType' failed to provide an identifier", id);
        obj = TermType.findTermType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'TermType' with identifier '" + id + "'", TermType.findTermType(id));
    }
    
}
