// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.AccomplishmentValue;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.AccomplishmentValueDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect AccomplishmentValueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AccomplishmentValueDataOnDemand: @Component;
    
    private Random AccomplishmentValueDataOnDemand.rnd = new SecureRandom();
    
    private List<AccomplishmentValue> AccomplishmentValueDataOnDemand.data;
    
    public AccomplishmentValue AccomplishmentValueDataOnDemand.getNewTransientAccomplishmentValue(int index) {
        AccomplishmentValue obj = new AccomplishmentValue();
        return obj;
    }
    
    public AccomplishmentValue AccomplishmentValueDataOnDemand.getSpecificAccomplishmentValue(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        AccomplishmentValue obj = data.get(index);
        Long id = obj.getId();
        return AccomplishmentValue.findAccomplishmentValue(id);
    }
    
    public AccomplishmentValue AccomplishmentValueDataOnDemand.getRandomAccomplishmentValue() {
        init();
        AccomplishmentValue obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return AccomplishmentValue.findAccomplishmentValue(id);
    }
    
    public boolean AccomplishmentValueDataOnDemand.modifyAccomplishmentValue(AccomplishmentValue obj) {
        return false;
    }
    
    public void AccomplishmentValueDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = AccomplishmentValue.findAccomplishmentValueEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'AccomplishmentValue' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<AccomplishmentValue>();
        for (int i = 0; i < 10; i++) {
            AccomplishmentValue obj = getNewTransientAccomplishmentValue(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
