// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.AccomplishmentValue;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.AccomplishmentValueDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.AccomplishmentValueIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AccomplishmentValueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AccomplishmentValueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AccomplishmentValueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AccomplishmentValueIntegrationTest: @Transactional;
    
    @Autowired
    private AccomplishmentValueDataOnDemand AccomplishmentValueIntegrationTest.dod;
    
    @Test
    public void AccomplishmentValueIntegrationTest.testCountAccomplishmentValues() {
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", dod.getRandomAccomplishmentValue());
        long count = AccomplishmentValue.countAccomplishmentValues();
        Assert.assertTrue("Counter for 'AccomplishmentValue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testFindAccomplishmentValue() {
        AccomplishmentValue obj = dod.getRandomAccomplishmentValue();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to provide an identifier", id);
        obj = AccomplishmentValue.findAccomplishmentValue(id);
        Assert.assertNotNull("Find method for 'AccomplishmentValue' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AccomplishmentValue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testFindAllAccomplishmentValues() {
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", dod.getRandomAccomplishmentValue());
        long count = AccomplishmentValue.countAccomplishmentValues();
        Assert.assertTrue("Too expensive to perform a find all test for 'AccomplishmentValue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AccomplishmentValue> result = AccomplishmentValue.findAllAccomplishmentValues();
        Assert.assertNotNull("Find all method for 'AccomplishmentValue' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AccomplishmentValue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testFindAccomplishmentValueEntries() {
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", dod.getRandomAccomplishmentValue());
        long count = AccomplishmentValue.countAccomplishmentValues();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AccomplishmentValue> result = AccomplishmentValue.findAccomplishmentValueEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AccomplishmentValue' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AccomplishmentValue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testFlush() {
        AccomplishmentValue obj = dod.getRandomAccomplishmentValue();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to provide an identifier", id);
        obj = AccomplishmentValue.findAccomplishmentValue(id);
        Assert.assertNotNull("Find method for 'AccomplishmentValue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAccomplishmentValue(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AccomplishmentValue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testMergeUpdate() {
        AccomplishmentValue obj = dod.getRandomAccomplishmentValue();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to provide an identifier", id);
        obj = AccomplishmentValue.findAccomplishmentValue(id);
        boolean modified =  dod.modifyAccomplishmentValue(obj);
        Integer currentVersion = obj.getVersion();
        AccomplishmentValue merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AccomplishmentValue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", dod.getRandomAccomplishmentValue());
        AccomplishmentValue obj = dod.getNewTransientAccomplishmentValue(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AccomplishmentValue' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AccomplishmentValue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AccomplishmentValueIntegrationTest.testRemove() {
        AccomplishmentValue obj = dod.getRandomAccomplishmentValue();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AccomplishmentValue' failed to provide an identifier", id);
        obj = AccomplishmentValue.findAccomplishmentValue(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AccomplishmentValue' with identifier '" + id + "'", AccomplishmentValue.findAccomplishmentValue(id));
    }
    
}
