// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.EducationLevel;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.EducationLevelDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.EducationLevelIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EducationLevelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EducationLevelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EducationLevelIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EducationLevelIntegrationTest: @Transactional;
    
    @Autowired
    private EducationLevelDataOnDemand EducationLevelIntegrationTest.dod;
    
    @Test
    public void EducationLevelIntegrationTest.testCountEducationLevels() {
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", dod.getRandomEducationLevel());
        long count = EducationLevel.countEducationLevels();
        Assert.assertTrue("Counter for 'EducationLevel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EducationLevelIntegrationTest.testFindEducationLevel() {
        EducationLevel obj = dod.getRandomEducationLevel();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", obj);
        Long id = obj.getEducationLevelId();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to provide an identifier", id);
        obj = EducationLevel.findEducationLevel(id);
        Assert.assertNotNull("Find method for 'EducationLevel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EducationLevel' returned the incorrect identifier", id, obj.getEducationLevelId());
    }
    
    @Test
    public void EducationLevelIntegrationTest.testFindAllEducationLevels() {
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", dod.getRandomEducationLevel());
        long count = EducationLevel.countEducationLevels();
        Assert.assertTrue("Too expensive to perform a find all test for 'EducationLevel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EducationLevel> result = EducationLevel.findAllEducationLevels();
        Assert.assertNotNull("Find all method for 'EducationLevel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EducationLevel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EducationLevelIntegrationTest.testFindEducationLevelEntries() {
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", dod.getRandomEducationLevel());
        long count = EducationLevel.countEducationLevels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EducationLevel> result = EducationLevel.findEducationLevelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EducationLevel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EducationLevel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EducationLevelIntegrationTest.testFlush() {
        EducationLevel obj = dod.getRandomEducationLevel();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", obj);
        Long id = obj.getEducationLevelId();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to provide an identifier", id);
        obj = EducationLevel.findEducationLevel(id);
        Assert.assertNotNull("Find method for 'EducationLevel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEducationLevel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EducationLevel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EducationLevelIntegrationTest.testMergeUpdate() {
        EducationLevel obj = dod.getRandomEducationLevel();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", obj);
        Long id = obj.getEducationLevelId();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to provide an identifier", id);
        obj = EducationLevel.findEducationLevel(id);
        boolean modified =  dod.modifyEducationLevel(obj);
        Integer currentVersion = obj.getVersion();
        EducationLevel merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getEducationLevelId(), id);
        Assert.assertTrue("Version for 'EducationLevel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EducationLevelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", dod.getRandomEducationLevel());
        EducationLevel obj = dod.getNewTransientEducationLevel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'EducationLevel' identifier to be null", obj.getEducationLevelId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'EducationLevel' identifier to no longer be null", obj.getEducationLevelId());
    }
    
    @Test
    public void EducationLevelIntegrationTest.testRemove() {
        EducationLevel obj = dod.getRandomEducationLevel();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to initialize correctly", obj);
        Long id = obj.getEducationLevelId();
        Assert.assertNotNull("Data on demand for 'EducationLevel' failed to provide an identifier", id);
        obj = EducationLevel.findEducationLevel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EducationLevel' with identifier '" + id + "'", EducationLevel.findEducationLevel(id));
    }
    
}
