// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.EducationLevel;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.EducationLevelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EducationLevelDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EducationLevelDataOnDemand: @Component;
    
    private Random EducationLevelDataOnDemand.rnd = new SecureRandom();
    
    private List<EducationLevel> EducationLevelDataOnDemand.data;
    
    public EducationLevel EducationLevelDataOnDemand.getNewTransientEducationLevel(int index) {
        EducationLevel obj = new EducationLevel();
        return obj;
    }
    
    public EducationLevel EducationLevelDataOnDemand.getSpecificEducationLevel(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EducationLevel obj = data.get(index);
        Long id = obj.getId();
        return EducationLevel.findEducationLevel(id);
    }
    
    public EducationLevel EducationLevelDataOnDemand.getRandomEducationLevel() {
        init();
        EducationLevel obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return EducationLevel.findEducationLevel(id);
    }
    
    public boolean EducationLevelDataOnDemand.modifyEducationLevel(EducationLevel obj) {
        return false;
    }
    
    public void EducationLevelDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EducationLevel.findEducationLevelEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EducationLevel' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EducationLevel>();
        for (int i = 0; i < 10; i++) {
            EducationLevel obj = getNewTransientEducationLevel(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
