// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.SchoolType;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.SchoolTypeDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.education.SchoolTypeIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SchoolTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SchoolTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SchoolTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SchoolTypeIntegrationTest: @Transactional;
    
    @Autowired
    private SchoolTypeDataOnDemand SchoolTypeIntegrationTest.dod;
    
    @Test
    public void SchoolTypeIntegrationTest.testCountSchoolTypes() {
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", dod.getRandomSchoolType());
        long count = SchoolType.countSchoolTypes();
        Assert.assertTrue("Counter for 'SchoolType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testFindSchoolType() {
        SchoolType obj = dod.getRandomSchoolType();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to provide an identifier", id);
        obj = SchoolType.findSchoolType(id);
        Assert.assertNotNull("Find method for 'SchoolType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SchoolType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testFindAllSchoolTypes() {
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", dod.getRandomSchoolType());
        long count = SchoolType.countSchoolTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'SchoolType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SchoolType> result = SchoolType.findAllSchoolTypes();
        Assert.assertNotNull("Find all method for 'SchoolType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SchoolType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testFindSchoolTypeEntries() {
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", dod.getRandomSchoolType());
        long count = SchoolType.countSchoolTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SchoolType> result = SchoolType.findSchoolTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SchoolType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SchoolType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testFlush() {
        SchoolType obj = dod.getRandomSchoolType();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to provide an identifier", id);
        obj = SchoolType.findSchoolType(id);
        Assert.assertNotNull("Find method for 'SchoolType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySchoolType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SchoolType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testMergeUpdate() {
        SchoolType obj = dod.getRandomSchoolType();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to provide an identifier", id);
        obj = SchoolType.findSchoolType(id);
        boolean modified =  dod.modifySchoolType(obj);
        Integer currentVersion = obj.getVersion();
        SchoolType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SchoolType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", dod.getRandomSchoolType());
        SchoolType obj = dod.getNewTransientSchoolType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SchoolType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SchoolType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SchoolTypeIntegrationTest.testRemove() {
        SchoolType obj = dod.getRandomSchoolType();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SchoolType' failed to provide an identifier", id);
        obj = SchoolType.findSchoolType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SchoolType' with identifier '" + id + "'", SchoolType.findSchoolType(id));
    }
    
}
