// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.education;

import cz.cvut.fit.mi_mpr_dip.admission.domain.education.SchoolDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect SchoolDataOnDemand_Roo_Configurable {
    
    declare @type: SchoolDataOnDemand: @Configurable;
    
}
