// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.personal;

import cz.cvut.fit.mi_mpr_dip.admission.domain.personal.Gender;
import cz.cvut.fit.mi_mpr_dip.admission.domain.personal.GenderDataOnDemand;
import cz.cvut.fit.mi_mpr_dip.admission.domain.personal.GenderIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect GenderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: GenderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: GenderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: GenderIntegrationTest: @Transactional;
    
    @Autowired
    private GenderDataOnDemand GenderIntegrationTest.dod;
    
    @Test
    public void GenderIntegrationTest.testCountGenders() {
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", dod.getRandomGender());
        long count = Gender.countGenders();
        Assert.assertTrue("Counter for 'Gender' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void GenderIntegrationTest.testFindGender() {
        Gender obj = dod.getRandomGender();
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", obj);
        Long id = obj.getGenderId();
        Assert.assertNotNull("Data on demand for 'Gender' failed to provide an identifier", id);
        obj = Gender.findGender(id);
        Assert.assertNotNull("Find method for 'Gender' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Gender' returned the incorrect identifier", id, obj.getGenderId());
    }
    
    @Test
    public void GenderIntegrationTest.testFindAllGenders() {
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", dod.getRandomGender());
        long count = Gender.countGenders();
        Assert.assertTrue("Too expensive to perform a find all test for 'Gender', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Gender> result = Gender.findAllGenders();
        Assert.assertNotNull("Find all method for 'Gender' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Gender' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void GenderIntegrationTest.testFindGenderEntries() {
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", dod.getRandomGender());
        long count = Gender.countGenders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Gender> result = Gender.findGenderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Gender' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Gender' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void GenderIntegrationTest.testFlush() {
        Gender obj = dod.getRandomGender();
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", obj);
        Long id = obj.getGenderId();
        Assert.assertNotNull("Data on demand for 'Gender' failed to provide an identifier", id);
        obj = Gender.findGender(id);
        Assert.assertNotNull("Find method for 'Gender' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyGender(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Gender' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GenderIntegrationTest.testMergeUpdate() {
        Gender obj = dod.getRandomGender();
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", obj);
        Long id = obj.getGenderId();
        Assert.assertNotNull("Data on demand for 'Gender' failed to provide an identifier", id);
        obj = Gender.findGender(id);
        boolean modified =  dod.modifyGender(obj);
        Integer currentVersion = obj.getVersion();
        Gender merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getGenderId(), id);
        Assert.assertTrue("Version for 'Gender' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void GenderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", dod.getRandomGender());
        Gender obj = dod.getNewTransientGender(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Gender' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Gender' identifier to be null", obj.getGenderId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Gender' identifier to no longer be null", obj.getGenderId());
    }
    
    @Test
    public void GenderIntegrationTest.testRemove() {
        Gender obj = dod.getRandomGender();
        Assert.assertNotNull("Data on demand for 'Gender' failed to initialize correctly", obj);
        Long id = obj.getGenderId();
        Assert.assertNotNull("Data on demand for 'Gender' failed to provide an identifier", id);
        obj = Gender.findGender(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Gender' with identifier '" + id + "'", Gender.findGender(id));
    }
    
}
