// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.address;

import cz.cvut.fit.mi_mpr_dip.admission.domain.address.PrintLine;
import cz.cvut.fit.mi_mpr_dip.admission.domain.address.PrintLineDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PrintLineDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PrintLineDataOnDemand: @Component;
    
    private Random PrintLineDataOnDemand.rnd = new SecureRandom();
    
    private List<PrintLine> PrintLineDataOnDemand.data;
    
    public PrintLine PrintLineDataOnDemand.getNewTransientPrintLine(int index) {
        PrintLine obj = new PrintLine();
        setName(obj, index);
        setValue(obj, index);
        return obj;
    }
    
    public void PrintLineDataOnDemand.setName(PrintLine obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void PrintLineDataOnDemand.setValue(PrintLine obj, int index) {
        String value = "value_" + index;
        obj.setValue(value);
    }
    
    public PrintLine PrintLineDataOnDemand.getSpecificPrintLine(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        PrintLine obj = data.get(index);
        Long id = obj.getPrintLineId();
        return PrintLine.findPrintLine(id);
    }
    
    public PrintLine PrintLineDataOnDemand.getRandomPrintLine() {
        init();
        PrintLine obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getPrintLineId();
        return PrintLine.findPrintLine(id);
    }
    
    public boolean PrintLineDataOnDemand.modifyPrintLine(PrintLine obj) {
        return false;
    }
    
    public void PrintLineDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = PrintLine.findPrintLineEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'PrintLine' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<PrintLine>();
        for (int i = 0; i < 10; i++) {
            PrintLine obj = getNewTransientPrintLine(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
