// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cz.cvut.fit.mi_mpr_dip.admission.domain.admission;

import cz.cvut.fit.mi_mpr_dip.admission.domain.admission.Term;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Term_Roo_Configurable {
    
    declare @type: Term: @Configurable;
    
}
